rhizo_base: Add quotes to sip_central_ip_address
The sip_central_ip_address in this template should be a python string,
and needs to be quoted like the other single string parameters. This
addresses the following error:

```
Traceback (most recent call last):
  File "./install.py", line 37, in <module>
    from config_values import *
  File "/var/rhizomatica/rccn/config_values.py", line 34
    sip_central_ip_address = 127.0.0.1
                                   ^
SyntaxError: invalid syntax
```